spring.application.name=employee-management-system
server.port=8086

spring.datasource.url=jdbc:h2:mem:emsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Auditing config
spring.jpa.properties.hibernate.show_sql=true

# Hibernate Batch Processing Configuration
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Initialize schema and data
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
