CREATE TABLE Customers (
    CustomerID NUMBER PRIMARY KEY,
    Name VARCHAR2(100),
    Age NUMBER,
    Balance NUMBER,
    IsVIP VARCHAR2(5)
);

CREATE TABLE Loans (
    LoanID NUMBER PRIMARY KEY,
    CustomerID NUMBER,
    InterestRate NUMBER(5,2),
    DueDate DATE,
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);

INSERT INTO Customers VALUES (1,'John',65,12000,'FALSE');
INSERT INTO Customers VALUES (2,'Alice',45,8000,'FALSE');
INSERT INTO Customers VALUES (3,'Bob',70,15000,'FALSE');
INSERT INTO Customers VALUES (4,'David',30,5000,'FALSE');
INSERT INTO Customers VALUES (5,'Emma',61,25000,'FALSE');

INSERT INTO Loans VALUES (101,1,8.5,SYSDATE+10);
INSERT INTO Loans VALUES (102,2,9.0,SYSDATE+40);
INSERT INTO Loans VALUES (103,3,8.0,SYSDATE+20);
INSERT INTO Loans VALUES (104,4,7.5,SYSDATE+15);
INSERT INTO Loans VALUES (105,5,8.2,SYSDATE+5);

COMMIT;

SELECT * FROM Customers;
SELECT * FROM loans;